controller_list:
  - name: object_iiwa/EffortJointInterface_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - object_iiwa_joint_1
      - object_iiwa_joint_2
      - object_iiwa_joint_3
      - object_iiwa_joint_4
      - object_iiwa_joint_5
      - object_iiwa_joint_6
      - object_iiwa_joint_7
