# Hand iiwa -----------------------------------
#sr_iiwa:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  

  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
    
  EffortJointInterface_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7
    gains:
      hand_iiwa_joint_1: {p: 500,  d: 30, i: 15, i_clamp: 30}
      hand_iiwa_joint_2: {p: 200,  d: 10, i: 10, i_clamp: 30}
      hand_iiwa_joint_3: {p: 65,  d: 10, i: 15, i_clamp: 30}
      hand_iiwa_joint_4: {p: 31,  d: 7, i: 12, i_clamp: 30}
      hand_iiwa_joint_5: {p: 23,  d: 3, i: 5, i_clamp: 30}
      hand_iiwa_joint_6: {p: 13,  d: 3, i: 3, i_clamp: 30}
      hand_iiwa_joint_7: {p: 17,  d: 2, i: 2.5, i_clamp: 10}
      
    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
