  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 500  

  PositionJointInterface_trajectory_controller:
    type: position_controllers/JointTrajectoryController
    joints: 
      - object_iiwa_joint_1
      - object_iiwa_joint_2
      - object_iiwa_joint_3
      - object_iiwa_joint_4
      - object_iiwa_joint_5
      - object_iiwa_joint_6
      - object_iiwa_joint_7

    constraints:
      goal_time: 0.5                   # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
    
  EffortJointInterface_trajectory_controller:
    type: effort_controllers/JointTrajectoryController
    joints: 
      - object_iiwa_joint_1
      - object_iiwa_joint_2
      - object_iiwa_joint_3
      - object_iiwa_joint_4
      - object_iiwa_joint_5
      - object_iiwa_joint_6
      - object_iiwa_joint_7
    gains:
      object_iiwa_joint_1: {p: 1000,  d: 50, i: 0.01, i_clamp: 100}
      object_iiwa_joint_2: {p: 5000,  d: 50, i: 0.1, i_clamp: 100}
      object_iiwa_joint_3: {p: 1000,  d: 1.0, i: 0.1, i_clamp: 100}
      object_iiwa_joint_4: {p: 5000,  d: 30, i: 0.1, i_clamp: 100}
      object_iiwa_joint_5: {p: 1000,  d: 1.0, i: 0.1, i_clamp: 100}
      object_iiwa_joint_6: {p: 3000,  d: 0.1, i: 0.01, i_clamp: 100}
      object_iiwa_joint_7: {p: 10,  d: 0, i: 0, i_clamp: 100}
      
    constraints:
      goal_time: 1                  # Override default

    state_publish_rate:  500            # Override default
    action_monitor_rate: 500            # Override default
    stop_trajectory_duration: 0        # Override default
