lh_trajectory_controller:
  type: "position_controllers/JointTrajectoryController"
  joints:
    - lh_FFJ1
    - lh_FFJ2
    - lh_FFJ3
    - lh_FFJ4
    - lh_MFJ1
    - lh_MFJ2
    - lh_MFJ3
    - lh_MFJ4
    - lh_RFJ1
    - lh_RFJ2
    - lh_RFJ3
    - lh_RFJ4
    - lh_THJ1
    - lh_THJ2
    - lh_THJ4
    - lh_THJ5
 
  stop_trajectory_duration: 0.5
  allow_partial_joints_goal: true
