controller_list:
  - name: fake_hand_iiwa_controller
    joints:
      - hand_iiwa_joint_1
      - hand_iiwa_joint_2
      - hand_iiwa_joint_3
      - hand_iiwa_joint_4
      - hand_iiwa_joint_5
      - hand_iiwa_joint_6
      - hand_iiwa_joint_7
      - lh_THJ5
      - lh_THJ4
      - lh_THJ3
      - lh_THJ2
      - lh_THJ1
      - lh_FFJ4
      - lh_FFJ3
      - lh_FFJ2
      - lh_FFJ1
      - lh_MFJ4
      - lh_MFJ3
      - lh_MFJ2
      - lh_MFJ1
      - lh_RFJ4
      - lh_RFJ3
      - lh_RFJ2
      - lh_RFJ1
      - lh_LFJ5
      - lh_LFJ4
      - lh_LFJ3
      - lh_LFJ2
      - lh_LFJ1
